# Basic Spectral configuration demonstrating override issue
extends:
  - "spectral:oas"

rules:
  oas3-api-servers: "off"
  info-contact: "off"
  info-description: "off"
  operation-operationId: "off"
  operation-description: "off"
  operation-tags: "off"

  cache-control-header-rule:
    description: "Example rule checking Cache-Control header"
    message: "Success responses should contain a `Cache-Control` header value of `no-store`."
    severity: "error"
    given: "$.paths[*][post,put,patch,delete].responses[200, 201, 204].headers.Cache-Control.description"
    then:
      function: "pattern"
      functionOptions:
        match: "no-store"

overrides:
  - files:
    - "/reference/api.yaml#/paths/resources~1details"
    rules:
      cache-control-header-rule: "off"
