openapi: 3.1.0
info:
  title: Test API
  version: 1.0.0
paths:
  /resources/details:
    post:
      summary: Example Endpoint
      responses:
        '200':
          description: OK
          headers:
            Cache-Control:
              $ref: 'shared/common.yaml#/components/headers/CacheControlHeader' 